### ISSUE TITLE
It might be helpful for daqinterface to use separate run_record_attempted directories per user

### ISSUE THREAD

**Issue by eflumerf** [art-daq/artdaq_daqinterface#108]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/15357 (FNAL account required)*
*Originally created by @bieryAtFnal on 2017-01-28 21:43:24*

----

or create the directory in /tmp with world write permissions.

Sat Jan 28 22:40:51 CET 2017: CONFIG transition underway
Sat Jan 28 22:40:51 CET 2017: Config name: demo_safemode
Sat Jan 28 22:40:51 CET 2017: Selected DAQ comps: {'component01': ['localhost', '6305']}
Exception in thread threadable:
Traceback (most recent call last):
  File "/home/pduser/daqsw/products/python/v2_7_11/Linux64bit+3.10-2.17/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/pduser/daqsw/products/python/v2_7_11/Linux64bit+3.10-2.17/lib/python2.7/threading.py", line 754, in run
    self.__target(**self.__args, ***self.__kwargs)
  File "/home/pduser/daqsw/lbneArtdaq/artdaq-utilities-daqinterface/rc/threading/*_init_*.py", line 15, in main
    self.func()
  File "rc/control/daqinterface.py", line 1797, in runner
    self.do_config()
  File "rc/control/daqinterface.py", line 1576, in do_config
    shutil.rmtree("/tmp/run_record_attempted")
  File "/home/pduser/daqsw/products/python/v2_7_11/Linux64bit+3.10-2.17/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/home/pduser/daqsw/products/python/v2_7_11/Linux64bit+3.10-2.17/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/tmp/run_record_attempted/metadata.txt'

**Comment by eflumerf** [comment]
*Comment by @jcfreeman2 on 2017-01-30 19:16:01*

----

With commit f71a23a23cfce7f6fa363d010e96285edbaa5e01, each user gets their own directory of the form "/tmp/run_record_attempted_<username>", where username is actually the value stored in the $USER environment variable.
