### ISSUE TITLE
save_run_record.py and Spack compatibility

### ISSUE THREAD

**Issue by eflumerf** [art-daq/artdaq_daqinterface#157]
We should revisit how DAQInterface collects package version information, given that it now usually runs out of a Spack environment instead of a git/MRB repository.

**Comment by ron003** [comment]
Output from DAQInterface:
...
Tue Dec  3 11:22:47 CST 2024: CONFIG transition underway
Config name: demo

Obtaining FHiCL documents...done (0.0 seconds).
Reformatting the FHiCL documents...done (0.1 seconds).
Bookkeeping the FHiCL documents...done (0.0 seconds).
Saving the run record...Warning: there was a problem trying to determine the version of package "artdaq_daqinterface"
Traceback (most recent call last):
  File "/home/nfs/ron/work/artdaqPrj/new4/local/install/rc/control/save_run_record.py", line 208, in save_run_record_base
    get_commit_info(
  File "/home/nfs/ron/work/artdaqPrj/new4/local/install/rc/control/utilities.py", line 658, in get_commit_info
    get_commit_hash(gitrepo),
  File "/home/nfs/ron/work/artdaqPrj/new4/local/install/rc/control/utilities.py", line 554, in get_commit_hash
    raise Exception(
Exception: 
Commit hash for "/home/nfs/ron/work/artdaqPrj/new4/local/install" not
found; this was requested in the "packages_hashes_to_save" list found in
/home/nfs/ron/work/artdaqPrj/new4/DAQInterface/settings_example

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nfs/ron/work/artdaqPrj/new4/local/install/rc/control/daqinterface.py", line 3661, in do_config
    self.save_run_record()
  File "/home/nfs/ron/work/artdaqPrj/new4/local/install/rc/control/save_run_record.py", line 218, in save_run_record_base
    % (self.package_versions["artdaq_daqinterface"])
KeyError: 'artdaq_daqinterface'


WARNING: an exception was thrown when attempting to save the run record.
While datataking may be able to proceed, this may also indicate a serious
problem
done (3.1 seconds).

Sending init transition to artdaq processes...done (1.1 seconds).

Longest individual transition was component01, which took 0.0 seconds.
All artdaq processes returned "Success".

Ensuring FHiCL documents will be archived in the output *.root files...done (0.1 seconds).
...
