### ISSUE TITLE
exception thrown when attempting to save the run record

### ISSUE THREAD

**Issue by eflumerf** [art-daq/artdaq_daqinterface#31]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/23168 (FNAL account required)*
*Originally created by @ron003 on 2019-08-24 02:23:05*

----

head of develop
Fri Aug 23 21:08:23 CDT 2019: CONFIG transition underway
Config name: demo

Obtaining FHiCL documents...done (0.0 seconds).
Bookkeeping the FHiCL documents...done (0.1 seconds).
Reformatting the FHiCL documents...done (0.4 seconds).
Saving the run record...Traceback (most recent call last):
  File "/home/ron/work/artdaqPrj/demo0-v3_06_00/artdaq-utilities-daqinterface/rc/control/daqinterface.py", line 1910, in do_config
    self.save_run_record()
  File "/home/ron/work/artdaqPrj/demo0-v3_06_00/artdaq-utilities-daqinterface/rc/control/save_run_record.py", line 160, in save_run_record_base
    self.fill_package_versions( [ string.replace(pkg, "-", "_") for pkg in packages_whose_versions_we_need ] )
  File "/home/ron/work/artdaqPrj/demo0-v3_06_00/artdaq-utilities-daqinterface/rc/control/daqinterface.py", line 1117, in fill_package_versions
    (package, version) = line.split()
ValueError: need more than 0 values to unpack

WARNING: an exception was thrown when attempting to save the run record.
While datataking may be able to proceed, this may also indicate a serious
problem
done (4.0 seconds).
component02 at localhost:14100, returned string is:
Success

component01 at localhost:14101, returned string is:
Success

EventBuilder1 at localhost:14102, returned string is:
Success

EventBuilder2 at localhost:14103, returned string is:
Success

DataLogger1 at localhost:14104, returned string is:
Success

Dispatcher1 at localhost:14105, returned string is:
Success

Ensuring FHiCL documents will be archived in the output *.root files...done (0.0 seconds).

Process manager logfiles (if applicable):

Fri Aug 23 21:08:28 CDT 2019: CONFIG transition complete

This causes problems when trying to use the database. The file "ranks.txt" is missing.

**Comment by eflumerf** [comment]
*Comment by @ron003 on 2019-08-24 02:28:16*

----

It appears that fill_package_versions has a problem when called with [] packages.

**Comment by eflumerf** [comment]
*Comment by @jcfreeman2 on 2019-08-26 19:24:58*

----

DAQInterface was creating a malformed regex when it wasn't asked to save any package versions via the "package_hashes_to_save" variable in $DAQINTERFACE_SETTINGS; this has been fixed at the head of feature/issue23168_support_not_saving_package_info (commit 63cab5db50293dc25f7fd433cf656a558857c31b)

**Comment by eflumerf** [comment]
*Comment by @jcfreeman2 on 2019-08-26 20:23:59*

----

Reviewed by Ron, success.
